name: Render Mkpage

on:
  push:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Render:
    runs-on: ubuntu-20.04
    container: 
      image: docker://pandoc/ubuntu:2.13
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      name: wget
        uses: wei/wget@v1
        with:
          args: mkpage.zip https://github.com/caltechlibrary/mkpage/releases/download/v1.0.3/mkpage-1.0.3-linux-amd64.zip   
      - name: unzip
        shell: bash
        run: unzip -qq mkpage.zip -mkpage
      - name: mv
        shell: bash
        run: mv mkpage/bin/mkpage .
      - name: ls
        shell: bash
        run: ls
      - name: chmod
        shell: bash
        run: chmod +x mkpage
      - name: Convert
        shell: bash
        run: ./mk-website.bash
